name: PNNL Push Mirror

on: [pull_request]

jobs:
  to_gitlab:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: ${{ secrets.GITLAB_REPO_URL }}
          GIT_USERNAME: ${{ secrets.GITLAB_USER }}
          GIT_PASSWORD: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GIT_PUSH_ARGS: --push-option=ci.skip --tags --force --prune
          PUSH_ALL_REFS: "false"
          DEBUG: "true"
      - uses: nelonoel/branch-name@v1.0.1
      - name: Trigger Pipeline
        run: |
          response=$(curl -X POST -F token=${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }} -F ref=${BRANCH_NAME} https://code.pnnl.gov/api/v4/projects/298/trigger/pipeline)
          exit_code=$?
          sudo apt install jq
          pipeline_id=$(echo $response | jq '.id' | sed 's/"//g')
          echo "PIPELINE_ID=${pipeline_id}" >> $GITHUB_ENV
          exit $exit_code
